// Mock data for the Halal Explorer website

// Featured destinations
export const featuredDestinations = [
  {
    id: 1,
    name: "Istanbul",
    country: "Turkey",
    region: "Middle East & Turkey",
    slug: "istanbul-turkey",
    description: "A vibrant city where East meets West, offering rich Islamic heritage and modern amenities.",
    imageUrl: "/placeholder.svg?height=400&width=600",
    rating: 4.8,
    reviewCount: 1245,
    tags: ["Historical", "Cultural", "Halal Food"],
    priceLevel: 3,
    features: ["Halal Food", "Prayer Facilities", "Muslim-Friendly Hotels", "Family Friendly"],
  },
  {
    id: 2,
    name: "Dubai",
    country: "United Arab Emirates",
    region: "Middle East & Turkey",
    slug: "dubai-uae",
    description: "A modern metropolis with luxurious shopping, stunning architecture, and Muslim-friendly amenities.",
    imageUrl: "/placeholder.svg?height=400&width=600",
    rating: 4.7,
    reviewCount: 987,
    tags: ["Luxury", "Shopping", "Family"],
    priceLevel: 5,
    features: ["Halal Food", "Prayer Facilities", "Muslim-Friendly Hotels", "Family Friendly"],
  },
  {
    id: 3,
    name: "Kuala Lumpur",
    country: "Malaysia",
    region: "Asia",
    slug: "kuala-lumpur-malaysia",
    description: "A multicultural hub with abundant halal food options, modern shopping, and Islamic attractions.",
    imageUrl: "/placeholder.svg?height=400&width=600",
    rating: 4.6,
    reviewCount: 856,
    tags: ["Food", "Shopping", "Budget-Friendly"],
    priceLevel: 2,
    features: ["Halal Food", "Prayer Facilities", "Muslim-Friendly Hotels", "Family Friendly"],
  },
  {
    id: 4,
    name: "Marrakech",
    country: "Morocco",
    region: "Africa",
    slug: "marrakech-morocco",
    description: "A colorful city with rich Islamic architecture, vibrant markets, and authentic Moroccan cuisine.",
    imageUrl: "/placeholder.svg?height=400&width=600",
    rating: 4.5,
    reviewCount: 723,
    tags: ["Historical", "Cultural", "Shopping"],
    priceLevel: 3,
    features: ["Halal Food", "Prayer Facilities", "Muslim-Friendly Hotels"],
  },
  {
    id: 5,
    name: "Maldives",
    country: "Maldives",
    region: "Asia",
    slug: "maldives",
    description: "Paradise islands with crystal clear waters, luxury resorts, and Muslim-friendly facilities.",
    imageUrl: "/placeholder.svg?height=400&width=600",
    rating: 4.9,
    reviewCount: 645,
    tags: ["Beach", "Luxury", "Honeymoon"],
    priceLevel: 5,
    features: ["Halal Food", "Prayer Facilities", "Muslim-Friendly Hotels"],
  },
  {
    id: 6,
    name: "Doha",
    country: "Qatar",
    region: "Middle East & Turkey",
    slug: "doha-qatar",
    description: "A rapidly developing city with modern architecture, cultural attractions, and Islamic heritage.",
    imageUrl: "/placeholder.svg?height=400&width=600",
    rating: 4.4,
    reviewCount: 512,
    tags: ["Modern", "Cultural", "Shopping"],
    priceLevel: 4,
    features: ["Halal Food", "Prayer Facilities", "Muslim-Friendly Hotels", "Family Friendly"],
  },
  {
    id: 7,
    name: "Cairo",
    country: "Egypt",
    region: "Middle East & Turkey",
    slug: "cairo-egypt",
    description: "Home to ancient wonders and Islamic landmarks with a rich cultural heritage.",
    imageUrl: "/placeholder.svg?height=400&width=600",
    rating: 4.3,
    reviewCount: 678,
    tags: ["Historical", "Cultural", "Budget-Friendly"],
    priceLevel: 2,
    features: ["Halal Food", "Prayer Facilities", "Family Friendly"],
  },
  {
    id: 8,
    name: "Bali",
    country: "Indonesia",
    region: "Asia",
    slug: "bali-indonesia",
    description: "A tropical paradise with increasing Muslim-friendly options and natural beauty.",
    imageUrl: "/placeholder.svg?height=400&width=600",
    rating: 4.2,
    reviewCount: 589,
    tags: ["Beach", "Nature", "Cultural"],
    priceLevel: 3,
    features: ["Halal Food", "Prayer Facilities"],
  },
  {
    id: 9,
    name: "London",
    country: "United Kingdom",
    region: "Europe",
    slug: "london-uk",
    description: "A global city with diverse Muslim communities, halal restaurants, and cultural attractions.",
    imageUrl: "/placeholder.svg?height=400&width=600",
    rating: 4.4,
    reviewCount: 734,
    tags: ["Urban", "Shopping", "Cultural"],
    priceLevel: 4,
    features: ["Halal Food", "Prayer Facilities", "Family Friendly"],
  },
  {
    id: 10,
    name: "Singapore",
    country: "Singapore",
    region: "Asia",
    slug: "singapore",
    description: "A clean, modern city-state with excellent halal food options and family-friendly attractions.",
    imageUrl: "/placeholder.svg?height=400&width=600",
    rating: 4.7,
    reviewCount: 823,
    tags: ["Modern", "Food", "Family"],
    priceLevel: 4,
    features: ["Halal Food", "Prayer Facilities", "Muslim-Friendly Hotels", "Family Friendly"],
  },
  {
    id: 11,
    name: "Amman",
    country: "Jordan",
    region: "Middle East & Turkey",
    slug: "amman-jordan",
    description: "A historic city with ancient ruins, vibrant markets, and authentic Middle Eastern cuisine.",
    imageUrl: "/placeholder.svg?height=400&width=600",
    rating: 4.3,
    reviewCount: 456,
    tags: ["Historical", "Cultural", "Budget-Friendly"],
    priceLevel: 2,
    features: ["Halal Food", "Prayer Facilities", "Family Friendly"],
  },
  {
    id: 12,
    name: "Sarajevo",
    country: "Bosnia and Herzegovina",
    region: "Europe",
    slug: "sarajevo-bosnia",
    description: "A European city with strong Islamic heritage, beautiful mosques, and halal cuisine.",
    imageUrl: "/placeholder.svg?height=400&width=600",
    rating: 4.5,
    reviewCount: 387,
    tags: ["Historical", "Cultural", "Budget-Friendly"],
    priceLevel: 2,
    features: ["Halal Food", "Prayer Facilities", "Family Friendly"],
  },
]

// All destinations (including featured)
export const allDestinations = [
  ...featuredDestinations,
  {
    id: 13,
    name: "Muscat",
    country: "Oman",
    region: "Middle East & Turkey",
    slug: "muscat-oman",
    description: "A coastal city with traditional Arabian architecture, beautiful mosques, and natural beauty.",
    imageUrl: "/placeholder.svg?height=400&width=600",
    rating: 4.4,
    reviewCount: 345,
    tags: ["Cultural", "Nature", "Relaxing"],
    priceLevel: 3,
    features: ["Halal Food", "Prayer Facilities", "Muslim-Friendly Hotels"],
  },
  {
    id: 14,
    name: "Casablanca",
    country: "Morocco",
    region: "Africa",
    slug: "casablanca-morocco",
    description: "Morocco's largest city with modern amenities, historic sites, and beautiful beaches.",
    imageUrl: "/placeholder.svg?height=400&width=600",
    rating: 4.2,
    reviewCount: 412,
    tags: ["Urban", "Beach", "Cultural"],
    priceLevel: 3,
    features: ["Halal Food", "Prayer Facilities", "Family Friendly"],
  },
  {
    id: 15,
    name: "Jakarta",
    country: "Indonesia",
    region: "Asia",
    slug: "jakarta-indonesia",
    description: "Indonesia's bustling capital with shopping malls, cultural sites, and abundant halal food.",
    imageUrl: "/placeholder.svg?height=400&width=600",
    rating: 4.0,
    reviewCount: 378,
    tags: ["Urban", "Shopping", "Food"],
    priceLevel: 2,
    features: ["Halal Food", "Prayer Facilities", "Family Friendly"],
  },
  {
    id: 16,
    name: "Abu Dhabi",
    country: "United Arab Emirates",
    region: "Middle East & Turkey",
    slug: "abu-dhabi-uae",
    description: "A modern city with stunning mosques, cultural attractions, and family-friendly activities.",
    imageUrl: "/placeholder.svg?height=400&width=600",
    rating: 4.6,
    reviewCount: 523,
    tags: ["Modern", "Cultural", "Family"],
    priceLevel: 4,
    features: ["Halal Food", "Prayer Facilities", "Muslim-Friendly Hotels", "Family Friendly"],
  },
  {
    id: 17,
    name: "Fez",
    country: "Morocco",
    region: "Africa",
    slug: "fez-morocco",
    description: "One of Morocco's oldest imperial cities with a well-preserved medieval medina.",
    imageUrl: "/placeholder.svg?height=400&width=600",
    rating: 4.5,
    reviewCount: 367,
    tags: ["Historical", "Cultural", "Shopping"],
    priceLevel: 2,
    features: ["Halal Food", "Prayer Facilities"],
  },
  {
    id: 18,
    name: "Medina",
    country: "Saudi Arabia",
    region: "Middle East & Turkey",
    slug: "medina-saudi-arabia",
    description: "The second holiest city in Islam with profound religious significance and history.",
    imageUrl: "/placeholder.svg?height=400&width=600",
    rating: 4.9,
    reviewCount: 876,
    tags: ["Religious", "Historical", "Cultural"],
    priceLevel: 3,
    features: ["Halal Food", "Prayer Facilities", "Muslim-Friendly Hotels"],
  },
]

// Regions for filtering
export const regions = ["Middle East & Turkey", "Asia", "Africa", "Europe", "North America", "South America", "Oceania"]

// Popular searches
export const popularSearches = [
  "Halal Beach Resorts",
  "Family Destinations",
  "Historical Islamic Sites",
  "Budget-Friendly",
  "Luxury Travel",
  "Winter Getaways",
  "Honeymoon Destinations",
]

// Mock prayer times
export const mockPrayerTimes = [
  { name: "Fajr", time: "05:23 AM" },
  { name: "Sunrise", time: "06:45 AM" },
  { name: "Dhuhr", time: "12:30 PM" },
  { name: "Asr", time: "03:45 PM" },
  { name: "Maghrib", time: "06:15 PM" },
  { name: "Isha", time: "07:45 PM" },
]

// Mock halal restaurants
export const mockHalalRestaurants = [
  {
    id: 1,
    name: "Authentic Flavors",
    cuisine: "Middle Eastern",
    priceRange: "$$",
    address: "123 Main Street",
    rating: 4.7,
    reviewCount: 245,
    certification: "Halal Certified",
    description:
      "Authentic Middle Eastern cuisine with a wide variety of halal options. Known for their kebabs and mezze platters.",
    imageUrl: "/placeholder.svg?height=300&width=400",
  },
  {
    id: 2,
    name: "Spice Garden",
    cuisine: "Indian",
    priceRange: "$$",
    address: "456 Oak Avenue",
    rating: 4.5,
    reviewCount: 187,
    certification: "Halal Certified",
    description:
      "Traditional Indian dishes with halal meat options. Their biryani and butter chicken are local favorites.",
    imageUrl: "/placeholder.svg?height=300&width=400",
  },
  {
    id: 3,
    name: "Mediterranean Delight",
    cuisine: "Mediterranean",
    priceRange: "$$$",
    address: "789 Pine Boulevard",
    rating: 4.8,
    reviewCount: 312,
    certification: "Muslim-Owned",
    description:
      "Upscale Mediterranean restaurant serving halal seafood, grilled meats, and fresh salads in an elegant setting.",
    imageUrl: "/placeholder.svg?height=300&width=400",
  },
]

// Mock mosques
export const mockMosques = [
  {
    id: 1,
    name: "Central Mosque",
    address: "123 Faith Street",
    description:
      "The largest mosque in the city, offering daily prayers, Jumu'ah, and special Ramadan programs. Features beautiful architecture and a community center.",
    facilities: ["Wudu Area", "Women's Section", "Parking", "Library", "Community Hall"],
    imageUrl: "/placeholder.svg?height=300&width=400",
  },
  {
    id: 2,
    name: "Islamic Cultural Center",
    address: "456 Harmony Road",
    description:
      "A modern mosque and cultural center offering prayer spaces, educational programs, and community events. Open to visitors of all faiths.",
    facilities: ["Wudu Area", "Women's Section", "Parking", "Bookstore", "Classrooms"],
    imageUrl: "/placeholder.svg?height=300&width=400",
  },
  {
    id: 3,
    name: "Historic Masjid",
    address: "789 Heritage Lane",
    description:
      "A historic mosque dating back several centuries, featuring traditional Islamic architecture and calligraphy. A must-visit for those interested in Islamic heritage.",
    facilities: ["Wudu Area", "Women's Section", "Tour Guides", "Gift Shop"],
    imageUrl: "/placeholder.svg?height=300&width=400",
  },
]

// Mock attractions
export const mockAttractions = [
  {
    id: 1,
    name: "Grand Palace",
    category: "Historical",
    duration: "2-3 hours",
    rating: 4.7,
    reviewCount: 1245,
    description:
      "A stunning palace complex featuring beautiful architecture and historical significance. A must-visit attraction.",
    imageUrl: "/placeholder.svg?height=300&width=400",
  },
  {
    id: 2,
    name: "Islamic Art Museum",
    category: "Cultural",
    duration: "1-2 hours",
    rating: 4.6,
    reviewCount: 876,
    description: "Explore the rich heritage of Islamic art and artifacts from various periods and regions.",
    imageUrl: "/placeholder.svg?height=300&width=400",
  },
  {
    id: 3,
    name: "Botanical Gardens",
    category: "Nature",
    duration: "2-3 hours",
    rating: 4.5,
    reviewCount: 654,
    description: "Beautiful gardens featuring local and exotic plants. Perfect for a relaxing day outdoors.",
    imageUrl: "/placeholder.svg?height=300&width=400",
  },
  {
    id: 4,
    name: "Old Market",
    category: "Shopping",
    duration: "2-4 hours",
    rating: 4.4,
    reviewCount: 987,
    description:
      "Traditional market offering local crafts, spices, textiles, and souvenirs. Great for experiencing local culture.",
    imageUrl: "/placeholder.svg?height=300&width=400",
  },
  {
    id: 5,
    name: "Coastal Promenade",
    category: "Outdoor",
    duration: "1-2 hours",
    rating: 4.3,
    reviewCount: 543,
    description: "A beautiful waterfront walkway with stunning views, cafes, and recreational areas.",
    imageUrl: "/placeholder.svg?height=300&width=400",
  },
  {
    id: 6,
    name: "Adventure Park",
    category: "Family",
    duration: "3-5 hours",
    rating: 4.5,
    reviewCount: 765,
    description: "Family-friendly park with rides, games, and activities suitable for all ages.",
    imageUrl: "/placeholder.svg?height=300&width=400",
  },
]
