import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    remotePatterns: [
      { protocol: 'https', hostname: 'cdn.sanity.io', pathname: '/**' },
      { protocol: 'https', hostname: 'source.unsplash.com', pathname: '/**' },
      { protocol: 'https', hostname: 'images.unsplash.com', pathname: '/**' },
    ],
  },
  async redirects() {
    return [
      // Deleted/Unpublished Blogs
      { source: '/blog/apps-halal-food-abroad', destination: '/blog', permanent: true },
      { source: '/blog/best-budget-muslim-friendly-destinations-under-50-dollars', destination: '/blog', permanent: true },
      { source: '/blog/best-muslim-friendly-destinations-2025', destination: '/blog', permanent: true },
      { source: '/blog/budget-halal-travel-save-money-without-sacrificing-faith', destination: '/blog', permanent: true },
      { source: '/blog/budget-halal-travel', destination: '/blog', permanent: true },
      { source: '/blog/budgeting-first-hajj-trip', destination: '/destinations/makkah', permanent: true },
      { source: '/blog/complete-halal-travel-packing-list-muslim-travelers', destination: '/blog/modest-packing-checklist-climates', permanent: true },
      { source: '/blog/complete-halal-travel-packing-list', destination: '/blog/modest-packing-checklist-climates', permanent: true },
      { source: '/blog/digital-tools-every-halal-traveler-should-have', destination: '/blog', permanent: true },
      { source: '/blog/dubai-secret-souks', destination: '/destinations/dubai', permanent: true },
      { source: '/blog/halal-cafes-london-notting-hill', destination: '/destinations/london', permanent: true },
      { source: '/blog/halal-food-europe-ultimate-guide-muslim-dining', destination: '/blog', permanent: true },
      { source: '/blog/halal-food-hopping-london-where-to-eat', destination: '/destinations/london', permanent: true },
      { source: '/blog/halal-food-hopping-london', destination: '/destinations/london', permanent: true },
      { source: '/blog/halal-food-hunting-tokyo', destination: '/destinations/tokyo', permanent: true },
      { source: '/blog/halal-food-japan-complete-guide-muslim-friendly-dining', destination: '/destinations/tokyo', permanent: true },
      { source: '/blog/halal-food-markets-around-the-world', destination: '/blog', permanent: true },
      { source: '/blog/halal-friendly-honeymoon-ideas-around-the-world', destination: '/blog', permanent: true },
      { source: '/blog/halal-staycations-best-muslim-friendly-hotels-dubai', destination: '/destinations/dubai', permanent: true },
      { source: '/blog/halal-street-food-guide-kuala-lumpur-must-try-dishes', destination: '/destinations/kuala-lumpur', permanent: true },
      { source: '/blog/halal-travel-packing-list-essentials', destination: '/blog/modest-packing-checklist-climates', permanent: true },
      { source: '/blog/how-to-choose-a-halal-friendly-tour-operator', destination: '/blog', permanent: true },
      { source: '/blog/how-to-evaluate-halal-certification-on-the-go', destination: '/blog', permanent: true },
      { source: '/blog/how-to-get-halal-certified-food-while-traveling-guide', destination: '/blog', permanent: true },
      { source: '/blog/islamic-heritage-trails-cultural-routes', destination: '/blog', permanent: true },
      { source: '/blog/islamic-history-cordoba', destination: '/blog', permanent: true },
      { source: '/blog/kuala-lumpur-budget-halal', destination: '/destinations/kuala-lumpur', permanent: true },
      { source: '/blog/malaysia-vs-turkey-vs-uae-best-muslim-travelers', destination: '/blog', permanent: true },
      { source: '/blog/muslim-friendly-3-day-itinerary-kuala-lumpur', destination: '/destinations/kuala-lumpur', permanent: true },
      { source: '/blog/muslim-friendly-adventure-travel-hiking-nature-escapes', destination: '/blog', permanent: true },
      { source: '/blog/muslim-friendly-cruise-options-what-to-expect', destination: '/blog', permanent: true },
      { source: '/blog/muslim-traveler-carry-on-essentials', destination: '/blog/modest-packing-checklist-climates', permanent: true },
      { source: '/blog/muslimah-guide-scandinavia', destination: '/blog', permanent: true },
      { source: '/blog/prayer-spaces-airports', destination: '/blog/how-to-find-prayer-spaces-when-traveling', permanent: true },
      { source: '/blog/ramadan-travel-destinations-tips', destination: '/blog/ramadan-travel-guide-fasting-while-traveling', permanent: true },
      { source: '/blog/ramadan-travel-how-to-plan-a-meaningful-trip', destination: '/blog/ramadan-travel-guide-fasting-while-traveling', permanent: true },
      { source: '/blog/ramadan-travel-plan-meaningful-trip', destination: '/blog/ramadan-travel-guide-fasting-while-traveling', permanent: true },
      { source: '/blog/top-10-halal-friendly-beach-resorts-worldwide', destination: '/blog/best-halal-beach-destinations-for-families', permanent: true },
      { source: '/blog/top-halal-friendly-shopping-kuala-lumpur', destination: '/destinations/kuala-lumpur', permanent: true },
      { source: '/blog/top-halal-friendly-shopping-kl', destination: '/destinations/kuala-lumpur', permanent: true },
      { source: '/blog/top-muslim-friendly-cities-europe-2025', destination: '/blog', permanent: true },
      { source: '/blog/travel-apps-prayer-rooms', destination: '/blog/how-to-find-prayer-spaces-when-traveling', permanent: true },
      { source: '/blog/ultimate-halal-foodie-guide-marrakech', destination: '/destinations/marrakech', permanent: true },

      // Deleted/Unpublished Destinations
      { source: '/destinations/algiers', destination: '/destinations', permanent: true },
      { source: '/destinations/birmingham-uk', destination: '/destinations/london', permanent: true },
      { source: '/destinations/brussels', destination: '/destinations', permanent: true },
      { source: '/destinations/colombo', destination: '/destinations', permanent: true },
      { source: '/destinations/cordoba', destination: '/destinations', permanent: true },
      { source: '/destinations/dhaka', destination: '/destinations', permanent: true },
      { source: '/destinations/frankfurt', destination: '/destinations', permanent: true },
      { source: '/destinations/george-town', destination: '/destinations/kuala-lumpur', permanent: true },
      { source: '/destinations/jeddah', destination: '/destinations/makkah', permanent: true },
      { source: '/destinations/kuala-terengganu', destination: '/destinations/kuala-lumpur', permanent: true },
      { source: '/destinations/kuwait-city', destination: '/destinations', permanent: true },
      { source: '/destinations/lahore', destination: '/destinations/islamabad', permanent: true },
      { source: '/destinations/langkawi', destination: '/destinations/kuala-lumpur', permanent: true },
      { source: '/destinations/maldives', destination: '/destinations', permanent: true },
      { source: '/destinations/mecca', destination: '/destinations/makkah', permanent: true },
      { source: '/destinations/medina', destination: '/destinations/madinah', permanent: true },
      { source: '/destinations/mumbai', destination: '/destinations/delhi', permanent: true },
      { source: '/destinations/osaka', destination: '/destinations/tokyo', permanent: true },
      { source: '/destinations/penang', destination: '/destinations/kuala-lumpur', permanent: true },
      { source: '/destinations/seoul', destination: '/destinations', permanent: true },
      { source: '/destinations/tashkent', destination: '/destinations/samarkand', permanent: true },
      { source: '/destinations/tunis', destination: '/destinations', permanent: true }
    ];
  },
};

export default nextConfig;