import { defineType, defineField } from 'sanity';

export const destination = defineType({
  name: 'destination',
  title: 'Destination',
  type: 'document',
  fields: [
    defineField({ name: 'name', type: 'string', title: 'Destination Name', validation: Rule => Rule.required() }),
    defineField({ name: 'slug', type: 'slug', title: 'Slug', options: { source: 'name' }, validation: Rule => Rule.required() }),
    defineField({ name: 'country', type: 'string', title: 'Country', validation: Rule => Rule.required() }),
    defineField({ name: 'description', type: 'text', title: 'Short Description' }),
    defineField({ name: 'intro', type: 'text', title: 'Intro Paragraph' }),
    defineField({ name: 'about', type: 'text', title: 'About Section' }),
    defineField({ name: 'details', type: 'array', title: 'Full Travel Guide (Portable Text)', of: [{ type: 'block' }] }),
    defineField({ name: 'image', type: 'image', title: 'Hero Image', options: { hotspot: true } }),
    defineField({ name: 'isFeatured', type: 'boolean', title: 'Featured Destination?' }),
    defineField({ name: 'whyMuslimsLoveIt', type: 'array', title: 'Why Muslims Love It', of: [{ type: 'string' }] }),
    defineField({ name: 'halalFoodInfo', type: 'text', title: 'Halal Food Info (Legacy String)' }),
    defineField({ name: 'prayerFacilities', type: 'text', title: 'Prayer Facilities Info (Legacy String)' }),
    defineField({ name: 'bestTimeToVisit', type: 'text', title: 'Best Time to Visit' }),
    defineField({ name: 'travelTips', type: 'array', title: 'Travel Tips', of: [{ type: 'string' }] }),
    defineField({ name: 'conclusion', type: 'text', title: 'Conclusion' }),
    defineField({
      name: 'quickFacts',
      type: 'object',
      title: 'Quick Facts',
      fields: [
        { name: 'currency', type: 'string', title: 'Currency' },
        { name: 'language', type: 'string', title: 'Main Language' },
        { name: 'visa', type: 'string', title: 'Visa Requirements' },
        { name: 'safety', type: 'string', title: 'Safety Level' },
        { name: 'timezone', type: 'string', title: 'Time Zone' },
        { name: 'dressCode', type: 'string', title: 'Dress Code' },
        { name: 'muslimPopulation', type: 'string', title: 'Muslim Population %' },
      ],
    }),
    defineField({
      name: 'muslimFriendlyScore',
      title: 'Muslim-Friendly Score (1–5)',
      type: 'number',
      validation: Rule => Rule.min(1).max(5),
      description: '1 = significant planning needed, 5 = effortlessly halal',
    }),
    defineField({
      name: 'ratings',
      title: 'Category Ratings',
      type: 'object',
      fields: [
        { name: 'halalFood', title: 'Halal Food (1–5)', type: 'number' },
        { name: 'mosques', title: 'Mosques (1–5)', type: 'number' },
        { name: 'modestDress', title: 'Modest Dress (1–5)', type: 'number' },
        { name: 'safety', title: 'Safety (1–5)', type: 'number' },
      ],
    }),
    defineField({
      name: 'halalFoodItems',
      title: 'Halal Food Items (Structured List)',
      type: 'array',
      of: [
        {
          type: 'object',
          fields: [
            { name: 'emoji', type: 'string', title: 'Emoji Icon' },
            { name: 'name', type: 'string', title: 'Dish or Restaurant Name' },
            { name: 'description', type: 'text', title: 'Description (1–2 sentences)' },
          ],
          preview: { select: { title: 'name', subtitle: 'description' } },
        },
      ],
    }),
    defineField({
      name: 'mosqueItems',
      title: 'Mosque & Prayer Facilities (Structured List)',
      type: 'array',
      of: [
        {
          type: 'object',
          fields: [
            { name: 'name', type: 'string', title: 'Mosque or Facility Name' },
            { name: 'description', type: 'text', title: 'Description' },
            { name: 'isLandmark', type: 'boolean', title: 'Is a Major Landmark?' },
          ],
          preview: { select: { title: 'name', subtitle: 'description' } },
        },
      ],
    }),
    defineField({
      name: 'affiliateProducts',
      title: 'Amazon Products — Pack for This Trip',
      type: 'array',
      description: 'Shown in the "Pack for This Trip" section. Add 3–5 relevant products.',
      of: [
        {
          type: 'object',
          fields: [
            { name: 'emoji', type: 'string', title: 'Product Emoji' },
            { name: 'label', type: 'string', title: 'Section Label (e.g. Prayer Essential)' },
            { name: 'productName', type: 'string', title: 'Product Name' },
            { name: 'description', type: 'text', title: 'Why this is relevant for this destination' },
            { name: 'amazonUrl', type: 'url', title: 'Amazon Affiliate URL (full URL with tag)' },
            { name: 'priceRange', type: 'string', title: 'Approx Price (e.g. AED 45–85 / $12–22)' },
          ],
          preview: { select: { title: 'productName', subtitle: 'label' } },
        },
      ],
    }),
    defineField({
      name: 'bookingComUrl',
      title: 'Booking.com Affiliate URL',
      type: 'url',
      description: 'Used in the sidebar "Book Hotels in [City]" CTA button',
    }),
    defineField({
      name: 'region',
      title: 'Region',
      type: 'string',
      options: {
        list: [
          { title: 'Middle East', value: 'middle-east' },
          { title: 'Southeast Asia', value: 'southeast-asia' },
          { title: 'South Asia', value: 'south-asia' },
          { title: 'Europe', value: 'europe' },
          { title: 'Africa', value: 'africa' },
          { title: 'East Asia', value: 'east-asia' },
          { title: 'Americas', value: 'americas' },
          { title: 'Central Asia', value: 'central-asia' },
          { title: 'Oceania', value: 'oceania' },
        ],
      },
    }),
    defineField({
      name: 'nearbyDestinations',
      title: 'Nearby Destinations (max 4)',
      type: 'array',
      of: [{ type: 'reference', to: [{ type: 'destination' }] }],
      validation: Rule => Rule.max(4),
    }),
    defineField({
      name: 'seoImage',
      title: 'SEO / Social Share Image (1200×630)',
      type: 'image',
      description: 'Used for OpenGraph. Different from the hero image. 1200×630px.',
    }),
    defineField({ name: 'metaTitle', type: 'string', title: 'Meta Title' }),
    defineField({ name: 'metaDescription', type: 'text', title: 'Meta Description' }),
    defineField({ name: 'metaKeywords', type: 'string', title: 'Meta Keywords' }),
    defineField({ name: 'canonicalUrl', type: 'url', title: 'Canonical URL' }),
  ],
});
